### ISSUE TITLE
Cannot save data using recovered fields

### ISSUE THREAD

**Issue by markhowellsmead** [BeAPI/ACF-PHP-Recovery#11]
This plugin seems to work well, in as far as it recovers the fields from my PHP script. The fields and all subfields, options, etc. appear in wp-admin as they should.

However, none of the values in the generated fields are saved. Editing pre-existing data (i.e. field content) produces the same result. Previously-saved field values are correctly displayed in wp-admin, but no modification of their values is saved. (e.g. the text in the WYSIWYG fields in the attached screenshot.)

![screen shot 2016-08-19 at 15 06 01](https://cloud.githubusercontent.com/assets/1571592/17810618/7910e560-661e-11e6-86ff-b1e8b4944473.jpg)

**Comment by petitphp** [comment]
Hi !

Thanks for the report. Can you tell us which version of WordPress and ACF you are using ?

**Comment by mhmli** [comment]
ACF 4 and PHP 7.

**Comment by petitphp** [comment]
Did you comment out the PHP code that load your fields after recovering them ?

With ACF v4, having the fields registered in WordPress admin and in PHP code can lead to weird behaviors and it might be why your fields values are not updating.

**Comment by mhmli** [comment]
Yes, I removed it once the fields were available in wp-admin.

**Comment by petitphp** [comment]
I tried several case with a WordPress 4.6, ACF 4.4.8, some addons like flexible fields and ACF PHP Recovery 0.2. And I was able to update the values after recovering them.

If you have not already try, can you disable all non required plugins and see if the issue is still there.

Also If you copy your php code registering the fields in a fresh WordPress install and use the tool to import them back do you have the same issue ?
