### ISSUE TITLE
Include the PHP for the ACF fieldsets generated from the PHP export.

### ISSUE THREAD

**Issue by jonatasu** [BeAPI/ACF-PHP-Recovery#16]
But... include where?

**Comment by MaximeCulea** [comment]
Hi @jonatasu,

The best way to include ACF Fields is through PHP, please find more details in [ACF's documentation](https://www.advancedcustomfields.com/resources/register-fields-via-php/).
Otherwise, to strictly answer your question, we use to include into a plugin or a theme.

The way to do it is the same, it depends only where you put the ACF PHP export file.
If we got a file call `fields.php`, the path to the fields could be :
- plugin => `wp-content/plugins/my-plugin/assets/acf/php/fields.php`
- theme => `wp-content/themes/my-theme/assets/acf/php/fields.php`

And then you include it with the following statement :
```
add_action( 'init', 'bea_register_fields' );
function bea_register_fields() {
	require_once( PATH_TO_FIELDS );
}
```

Does it sounds better now for you ?

**Comment by jonatasu** [comment]
Yeah, thanks @MaximeCulea ! I'll try later.

**Comment by MaximeCulea** [comment]
Hi @jonatasu,
Have you tried ?
Can we close this issue ?
Thx

**Comment by jonatasu** [comment]
Hello @MaximeCulea,
I'm not working on the project anymore, but I did't resolve this issue through a recent version of ACF.

We can close it, thanks!

**Comment by MaximeCulea** [comment]
👌 thx
